/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

public class App {
  public String getGreeting() {
    return "こんにちは SEMonster";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    String monster = new Monster(4, 10).toString();
    System.out.println(monster);
    Player player = new Player("滝廉太郎", 500);
    System.out.println(player.callPlayer());
  }
}
